modules:
  recipebugfix:
    enabled: true
  phantomspawnblocker:
    enabled: true
  endermanmushroombugfix:
    enabled: true
  itemloreandsignature:
    enabled: false

itemloreandsignature:
  forge:
    cost: 1000.0
    linear-increase-multiplier: 1.5
