name: TianjiCore
version: ${project.version}
main: org.tianjiserver.tianjicore.TianjiCore
api-version: '26.2'
authors: [ Tianji-Community ]
softdepend: [ Vault ]
commands:
  tianjicore:
    description: TianjiCore 管理命令
    usage: /tianjicore [forge|lore|toggle|reload]
permissions:
  tianjicore.command.forge:
    description: 使用锻造命令添加、修改、删除物品 lore
    default: true
  tianjicore.command.admin:
    description: 使用 TianjiCore 管理命令
    default: op
